// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx8rlWyngQsszUNVRZqGGZTI6MnfidUW4',
    appId: '1:416528318034:web:598b42a87c1b5ab3dde98b',
    messagingSenderId: '416528318034',
    projectId: 'brickwall-b8bfb',
    authDomain: 'brickwall-b8bfb.firebaseapp.com',
    storageBucket: 'brickwall-b8bfb.appspot.com',
    measurementId: 'G-GGM92CF3EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpv-rHlaVaZ8yxLEddt9L-SOtGjMHLqs',
    appId: '1:416528318034:android:c07a892c48d74308dde98b',
    messagingSenderId: '416528318034',
    projectId: 'brickwall-b8bfb',
    storageBucket: 'brickwall-b8bfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZNhMz-iUEANXGVqD66L2MsoMw0pvPRXI',
    appId: '1:416528318034:ios:a12bbbbe3cdc9474dde98b',
    messagingSenderId: '416528318034',
    projectId: 'brickwall-b8bfb',
    storageBucket: 'brickwall-b8bfb.appspot.com',
    iosClientId: '416528318034-1nolmhitom907ss6lmqtg90tfat5j57u.apps.googleusercontent.com',
    iosBundleId: 'com.francisgonzales.brickwall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZNhMz-iUEANXGVqD66L2MsoMw0pvPRXI',
    appId: '1:416528318034:ios:90b367acb9c96a01dde98b',
    messagingSenderId: '416528318034',
    projectId: 'brickwall-b8bfb',
    storageBucket: 'brickwall-b8bfb.appspot.com',
    iosClientId: '416528318034-hbfangjcerdh0tie68eu2hq11jh9q0qg.apps.googleusercontent.com',
    iosBundleId: 'com.francisgonzales.brickwall.RunnerTests',
  );
}
